--require("basic")
--require("keymap")
--require("plugins")
--require("snippet")
--require("source")
--require('usermod.settings')
vim.g.mapleader = ","
vim.g.g:mapleader = ","

--vim.g.nocompatible = true
--vim.g.backspace = "eol,start,intend"
--vim.g.number = true
--vim.g.cursorline = true
--vim.g.tabstop = 4
--vim.g.shiftwidth = 4
--vim.g.softtabstop = 4
--vim.g.expandtab = true
--vim.g.smarttab = true
--vim.g.autoindent = true
--
--vim.g.showmatch = true
--
--vim.g.hlsearch = true
--vim.g.incsearch = true
--
--vim.g.syntax = true
--vim.g.t_color = 256
--vim.g.colorscheme = "gruvbox"
--
--vim.g.showcmd = true
--vim.g.wildmenu = true
--vim.g.wildmode = "list:longest,full"
--
--vim.g.hidden = true
--
--vim.g.splitright = true
--vim.g.splitbelow = true
--
--vim.g.filetype = "on"
--
--
